### ISSUE TITLE
VolumeRendering simplification thoughts

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#127]
PLaceholder for brainstorming a simpler UI for microCT datasets: 

There multiple recurring issues that can be easily addressed.

1.	We need a reasonable transfer function automatically calculated. This might be a simple ramp that covers the 90% of the data range.
2.	Current initial guess does an OK job, when the volume is rendered very first time in the scene. Say if you want to generate a new volume property, it starts from this solid rectangle that it you can’t make it anything into (at least not with a lot of work). Even worse, the only way to recover is to reset the scene.
3.	And of course data size…

I kind of like the idea of having a SlicerMorph specific volume rendering module that is integrated to the Data Module (right click on it and show it in 3D. Right now you have to have the right click on the eye icon). Or modify the data module to have specific 3D rendering colume (in addition to 2D visibility). 

Example of useless volume property generated when the user manually chooses "Create New VolumeProperty".
The initial:
![image](https://user-images.githubusercontent.com/21285140/102423192-4ee60b80-3fbd-11eb-8a25-67ea59fa28ac.png)
Subsequent ones:
![image](https://user-images.githubusercontent.com/21285140/102423204-55748300-3fbd-11eb-8ca2-9529ee16065c.png)

**Comment by pieper** [comment]
Yes, we need a better way to create and share rendering parameters.  This could also include special shaders via PRISMRendering.

Also I'm thinking there's no reason the preset thumbnails can't be generated on the fly with your actual data rather than showing canned icons.  I think Osirix has this feature.

We could also consider doing a sort of search interface were you are given a layout of render options and you click on the one you like and then are given another set of ones similar to what you picked.  Like a kind of genetic algorithm instead of a bunch of sliders.

We could also try to collect some kind of database to map features of the volume to render parameters that users ended up liking and use that to automatically determine the parameters for new data.

What Mike said yesterday about applying different volume rendering parameters in different parts of the image is also interesting.  E.g. using segmentations as masks to determine the render properties.  E.g. to get color from segment but translucency and detail from volume.

**Comment by muratmaga** [comment]
For the on-the-fly thumbnail generation, you should be cognizant that our datasets will be anywhere from 10-100 times larger than the toy MRHead or sample data. My primary motivation of simplifying the interface is for our users and for our types of datasets (large microCT). I invited Adam Summers, we will probably schedule a meeting next week.

**Comment by pieper** [comment]
That's the beauty of the on-the-fly thumbnails - they take basically no time to generate since you are just changing the transfer function and keeping a small screenshot.  As fast as dragging the slider, so if the thumbnails take any noticeable time then you probably won't be able to work with the data at all.

**Comment by muratmaga** [comment]
closing as this is now a much bigger discussion. SlicerMorph customization now include presets for diceCT (16 bit) and mouse/fish skulls (8 bit).
