### ISSUE TITLE
Improve ImageStacks

### ISSUE THREAD

**Issue by lassoan** [SlicerMorph/SlicerMorph#138]
Missing features that would make the module much more powerful:
- Crop volume during import. Simple non-interpolated, non-rotated cropping with the new markups ROI. It would completely alleviate the need to use ImageJ. It would also shift the origin, so this would address #74.
- Allow skipping more than 1 slices along any axis. It is nice that you any number of slices along Z axis, but skipping along X and Y axes are hardcoded to 0 or 1. if I want to have a quick preview or have an evenly downsampled volume then  there should be a way to specify skipping for X and Y axes, too.
- Compute output volume size from current frame (instead of just showing downsampled volume with no Z slice skipping)

**Comment by SlicerMorph** [comment]
We discussed these issues internally a few times. Out of those three, the most useful one is the crop at the time of import, since there are datasets with significant amount of background space that can be trimmed. However, this requires reading the stack very quick so that the user can manipulate the ROI to fit to real image extends.  ImageJ does this really well with the virtual stacks. We couldn't decide how to come up with this is an a simple way that woudln't confuse users even more. If you have suggestions on this, that would be great.

As for downsampling, anything beyond x2 reduces data quality extremely. Realistically I don't see anyone doing 4X reduction and obtain a usable volume. The difference between skipping slice is to accommodate full-body scans. Almost similar to the human imaging, you might be more interested in preserving the cross-sectional geometry (e.g., cranial sutures in a full body scan) but have coarser sampling in Z space. 

In the end, this particular use case can be accommodated by simply having this ROI/VOI concept above at the import time. 

So all in all, I think it is the ROI tool that's the most significant bang for the buck.

**Comment by lassoan** [comment]
All the suggestions are for allowing the user specify the ROI quickly.

> this requires reading the stack very quick so that the user can manipulate the ROI to fit to real image extends. ImageJ does this really well with the virtual stacks. We couldn't decide how to come up with this is an a simple way that woudln't confuse users even more. If you have suggestions on this, that would be great.

Simple skipping of frames, rows, columns work well. It is both very fast and reduces memory drastically.

> As for downsampling, anything beyond x2 reduces data quality extremely. Realistically I don't see anyone doing 4X reduction and obtain a usable volume. 

It is for preview. To have a quick look what is in the volume and specify clipping ROI.

If you prefer not to expose a lot of options to the user (make sense, less chance for messing things up) then we could have 3 quality levels:
- preview: determine frame, row, column skip values automatically to have an approximately 50MB volume (could be an advanced setting how much exactly, on a laptop I would set smaller value than on a desktop), it should be possible to load the preview within a couple of seconds
- half: use every second row/column
- full: no row/column skip

**Comment by muratmaga** [comment]
>     * preview: determine frame, row, column skip values automatically to have an approximately 50MB volume (could be an advanced setting how much exactly, on a laptop I would set smaller value than on a desktop), it should be possible to load the preview within a couple of seconds

So the flow would be something like:
* Preview the full extent of the dataset
* Set a ROI to define import bounds
* Then only load the image within the ROI at the specified resolution (full or downsampled)
* Provide the correct image offset etc...

Is that what you have in mind?

**Comment by lassoan** [comment]
Yes.

**Comment by muratmaga** [comment]
Thanks I think that flow makes sense. Unfortunately, unless you have bandwidth to take this on, this will wait a bit as we have to do the workshop, finish the paper revision and then come back to it...
