### ISSUE TITLE
Points placed incorrectly with the 'p' shortcut when display scaling is >100

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#156]
To reproduce:
1. Enable the SlicerMorph preferences (for p shortcut to work)
2. Set the display scaling to more than 100%
3. Restart slicer and load MRHead
4. Press p to place a landmark and note that there is a distinct offset between where the point is placed and where the cursor is actually is

Reproduces for me all the with my Windows 10 laptop with 4K screen.

**Comment by pieper** [comment]
To clarify, this is on windows?  Which version?  And which version of Slicer(Morph)?

**Comment by muratmaga** [comment]
Last version of SlicerMorph with latest stable. 
In mac it happens all the time (as far as we can test on Sara's Mac).

**Comment by pieper** [comment]
This looks like [a long-running issue in Qt](https://bugreports.qt.io/browse/QTBUG-62149?focusedCommentId=366202&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel).  Looks like it should be fixed in our version but maybe not.

The code we use relies on qt to do this mapping:

```
    cursorPosition = qt.QCursor.pos()
    widget = slicer.app.widgetAt(cursorPosition)
    mousePosition = widget.mapFromGlobal(cursorPosition)
```

so we could dig around to try to find a workaround, but it looks like a pretty deep problem.

The other option would be to capture the event at the vtk level instead of Qt.  This would mean you need to click in the render window to give it focus before you can place with the p key.
