### ISSUE TITLE
Dockerfile not working 

### ISSUE THREAD

**Issue by singhsaluja** [SlicerMorph/SlicerMorph#197]
Greetings, 
We are trying to build the docker image from the docker file provided in this repo but looks like the AWS links to download the packages (turbo-vnc etc.) are deprecated. 

```
WORKDIR /home/docker
"Dockerfile" 98L, 3019C                                                                                                                            94,3          Bot
Resolving download.slicer.org (download.slicer.org)... 66.162.65.219
Connecting to download.slicer.org (download.slicer.org)|66.162.65.219|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.slicer.org/bitstream/1442746 [following]
--2022-03-11 07:53:30--  https://download.slicer.org/bitstream/1442746
Connecting to download.slicer.org (download.slicer.org)|66.162.65.219|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://slicer-packages.kitware.com/api/v1/item/1442746/download [following]
--2022-03-11 07:53:30--  https://slicer-packages.kitware.com/api/v1/item/1442746/download
Resolving slicer-packages.kitware.com (slicer-packages.kitware.com)... 216.136.40.52
Connecting to slicer-packages.kitware.com (slicer-packages.kitware.com)|216.136.40.52|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-03-11 07:53:30 ERROR 400: Bad Request.
```
Is there a new docker file available or is there a pre-built image on dockerhub that we can get? Thank you for your time and help.

**Comment by muratmaga** [comment]
I am assuming you are working off this Dockerfile https://github.com/SlicerMorph/SlicerMorphCloud/blob/main/Dockerfile ?

Slicer download infrastructure has since changed, and I haven't tested with the new URLs (nor I know what they have became). Probably you want to ask on the SLicer discourse forum. However, nowadays I prefer not to embed the Slicer into the docker build, but simply download it onto a persistent storage attached to the docker instance. This makes upgrading/adding extensions much more easy (no need to rebuild the docker)
