### ISSUE TITLE
Add a feature to MarkupEditor for LM exclusion

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/SlicerMorph#199]
This is a feature request so that people can use the MarkupEditor to generate a LM exclusion list for the GPA module. What we need is the table number of the selected (excluded) fiducials to be returned as a comma-separated (no blanks in between) list copied to memory. When the user can directly paste this into the GPA module
@pieper what do you think?

**Comment by pieper** [comment]
Just catching up with this.  If I'm understanding correctly, it sounds like this should be a feature of the GPA module to pick a markups pointlist node and use the selected or unselected points.  It wouldn't make sense to me that the general purpose markup editor would have a feature that is specific to the GPA use case.

**Comment by pieper** [comment]
Okay, it's fine since this is all within the context of SlicerMorph.

In [this code](https://github.com/SlicerMorph/SlicerMorph/blob/e49727fd92c4bd383d116be29c4d8d385ae654a9/MarkupEditor/MarkupEditor.py#L58-L167) there just needs to be another entry for copying the indices to the clipboard.  The corresponding action code can use `slicer.app.clipboard().setText(indexListAsText)` to put it in the clipboard.  It should be very simple.

**Comment by SlicerMorph** [comment]
Thanks.
@smrolfe can you add an action to MarkupsEditor something like "copy selected points as missing in GPA". So that after that action, the user can paste the correctly formatted indices to the missing LM field in GPA?

**Comment by muratmaga** [comment]
@smrolfe we discussed this using the markup editor in context of subsetting the landmarks from DeCaL. It is a separate issue on the DeCA site (and not sure if you are going to address them simultaneously) but adding it for tracking purposes. 
https://github.com/smrolfe/DeCA/issues/5
