### ISSUE TITLE
ImageStacks TIFF warning/error

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#320]
Some dataset that generates this warning message for the tiff files in `ImageStacks`, slowing down the import to a crawl. Same dataset imported without ImageStacks, using Slicer's own load data, works fast and loads normally. 

Is there away to make ImageStacks ignore this field. This is the warning that constantly repeated. 

`
TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65281 (0xff01) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65281 (0xff01) encountered.
`

I added a short sequence of offending tiff files to the issue. 

@pieper @lassoan if you have suggestions it will be great. 

[sample.zip](https://github.com/SlicerMorph/SlicerMorph/files/14610818/sample.zip)

**Comment by pieper** [comment]
Probably it's this part:

https://github.com/SlicerMorph/SlicerMorph/blob/8af8a03a2ffdadec79cbc070e197e6f3daa26d86/ImageStacks/ImageStacks.py#L710-L712

I'm guessing this is a valid complaint for this data, but maybe not important in this use case.

Maybe the best would be to fix ITK to only issue one warning for this rather than repeating it or just ignore it (perhaps as an optional flag for backwards compatibility).

It would be good to try replicating in a small ITK script and then report an issue.

**Comment by muratmaga** [comment]
I don't really know how to use ITK direcly. But I use ANTsR which uses ITK to read image data, and it reports the same error. 
```R
> img = antsImageRead("Scan_0101__rec00000100.tif")
TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65281 (0xff01) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65281 (0xff01) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65281 (0xff01) encountered.
> img
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 1348x1420 
  Voxel Spacing       : 0.00900070871722183x0.00900070871722183 
  Origin              : 0 0 
  Direction           : 1 0 0 1 
  Filename           : Scan_0101__rec00000100.tif 
```

**Comment by pieper** [comment]
Then probably the best solution is to fix ITK so it improves behavior on all systems then.  That is, if you really think these are valid tiff that ITK should support.  I have no idea if this is malformed tif that requires a warning or if the ITK is wrong.

**Comment by muratmaga** [comment]
@pieper @lassoan this is turning to be quite blocking for large datasets. Until we have time to look into why these errors generated, would it be possible to just print one warning/error message and then ignore/suppress the rest. That's where the slowness is coming from, 3000-4000 messages being logged brings the read performance to a crawl.

**Comment by pieper** [comment]
From a small amount of searching [it appears this is in the tiff C library](https://unix.stackexchange.com/questions/154496/tiffreaddirectory-warning-unknown-field) so it's not impossible to change but would require digging in at the ITK level even just to limit the amount of output.  

Another option could be so use a [different tiff reading library](https://pypi.org/project/tifffile/) at the python level in the module, which would probably just require a branch of the code similar to the nrrd version.

**Comment by lassoan** [comment]
This issue is all over github and StackOverflow. It is crazy to think about the hundreds of thousands $ worth of effort wasted on this because of wrong decisions made by libtiff developers.

Anyway, what do you think about fixing this by suppressing all "unknown tag" warnings in ITK TIFF reader by registering a custom warning handler like this?

https://github.com/lassoan/ITK/commit/f85248f5378de26b0a57a3bd2cc843099e0a00cd

**Comment by muratmaga** [comment]
> This issue is all over github and StackOverflow. It is crazy to think about the hundreds of thousands $ worth of effort wasted on this because of wrong decisions made by libtiff developers.

To be clear, this is only happening in some of the tiff datasets, not all of them. It just turns out that effected data is coming from our scanner (Bruker Skyscan). I will reach out to the Bruker developers, but meanwhile to me ignoring (and not logging thousands of lines of messages to the log) is all I want.

**Comment by lassoan** [comment]
Many software use custom TIFF tags for storing custom metadata and that should be OK. LibTIFF printing hard-to-suppress warning messages is the issue (that is reported all over the internet).

@pieper what do you think about my proposed ITK change? I haven't made the message suppression configurable at runtime, because a proper solution would require a more recent libtiff version, which is threadsafe.

**Comment by pieper** [comment]
> @pieper what do you think about my proposed ITK change?

I like it.  I looked at that code and figured something like that would be needed, but I didn't actually do it so thanks for digging in.  This should probably go into Slicer/ITK right away and then also be suggested for upstream ITK.

**Comment by muratmaga** [comment]
@lassoan @pieper is this in Slicer/ITK now? Because I am still seeing the error in the latest preview?

**Comment by pieper** [comment]
Here's the fix Andras proposed.  

https://github.com/lassoan/ITK/commit/f85248f5378de26b0a57a3bd2cc843099e0a00cd

It looks good to me, so I guess the next step would be to create a pull request to upstream ITK and also merge the patch into Slicer/ITK and update the hash in the SuperBuild.

**Comment by muratmaga** [comment]
Ok my concern is making sure this changes integrated before the new stable is cut, as we primarily use the stable versions for our events.

Also @jcfr

**Comment by lassoan** [comment]
We should be able to include this fix in Slicer-5.8. If you want to make sure then enter an issue in Slicer's issue tracker and set the milestone to `Slicer 5.8`.

**Comment by muratmaga** [comment]
I created the issue, but I don't have write permission to the repo so I can neither assign nor set milestones. You are all cc'ed on the issue:

https://github.com/Slicer/Slicer/issues/7994

**Comment by muratmaga** [comment]
done via change in ITK. https://github.com/Slicer/Slicer/pull/8016
